### PR TITLE
added theme based colors for none theme specific coloring of calendar components

### PR DESCRIPTION
**Pull request by dark-eye**

### CODE REVIEW

**Comment by hummlbach** [comment]
Thanks for this really quick implementation! First the nits: Theres a typo in business as well as in leisure. :-P
Its not nice that we have to do that, and i don't have any clue concerning this theming stuff, but seems to be well done and a valid solution what you're suggesting there. :+1:  So maybe lets fix the typos and see what @mardytardi will say :-)

**Review by hummlbach — COMMENTED** [review]
Thanks for this really quick implementation! First the nits: Theres a typo in business as well as in leisure. :-P Its not nice that we have to do that, and i don't have any clue  concerning this theming stuff, but seems to be well done and a valid  solution what you're suggesting there.   So maybe lets fix the typos and see what @mardytardi will say :-) Do you want to fix the typos, or should I?

**Comment by dark-eye** [comment]
@hummlbach typos fixed :) (English first language not :P )

**Review by hummlbach — APPROVED** [review]
Thanks!

**Pull request merged**
